"""add shared with email to the conversation model

Revision ID: 20241003153813_827623103002
Revises: 20240927094023_fb0b353e69d0
Create Date: 2024-10-03 15:38:13.436502

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20241003153813_827623103002"
down_revision: Union[str, None] = "20240927094023_fb0b353e69d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("shared_with_emails", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "shared_with_emails")
    # ### end Alembic commands ###
