"""New migration

Revision ID: 20241028204107_684a330f9e9f
Revises: 20241003153813_827623103002
Create Date: 2024-10-28 20:41:07.469748

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20241028204107_684a330f9e9f"
down_revision: Union[str, None] = "20241003153813_827623103002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE visibility AS ENUM ('PRIVATE', 'PUBLIC')")
    op.add_column(
        "conversations",
        sa.Column(
            "visibility", sa.Enum("PRIVATE", "PUBLIC", name="visibility"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "visibility")
    op.execute("DROP TYPE visibility")
    # ### end Alembic commands ###
