"""Support for citations in backend

Revision ID: 20240927094023_fb0b353e69d0
Revises: 20240905144257_342902c88262
Create Date: 2024-09-27 09:40:23.874379

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20240927094023_fb0b353e69d0"
down_revision: Union[str, None] = "20240905144257_342902c88262"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("citations", sa.Text(), nullable=True))
    op.create_index(
        "idx_user_preferences_user_id", "user_preferences", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_preferences_user_id", table_name="user_preferences")
    op.drop_column("messages", "citations")
    # ### end Alembic commands ###
